# 請替換掉所有的${}
# 這個設定檔 for health check
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ${demo-backendconfig}
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    port: 8080
  logging:
    enable: true
    sampleRate: 1
  securityPolicy:
    name: security-policy
