# 請替換掉所有的${}
apiVersion: v1
kind: Service
metadata:
  name: ${demo-app-service}  # Name of the service
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8080":"${demo-backendconfig}"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: ${demo-app}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
